### ISSUE TITLE
can't use rm in command runner

### ISSUE THREAD

**Issue by at15** [dyweb/Ayi#58]
````yaml
scripts:
  clean:
    - rm *.aux
````

````
⇒  Ayi run clean
INFO[0000] executing: rm *.aux 
                        
rm: cannot remove '*.aux': No such file or directory
ERRO[0000] clean failed due to: Failure when executing command: exit status 1 
ERRO[0000] script failed    
````
